version: '2'

services:
  redis:
    image: redis
    command: redis-server . --maxmemory 100mb --maxmemory-policy allkeys-lru

  app:
    environment:
      - SZALINSKI_REDIS_HOST=redis
    build: ./
    ports:
      - "8080:8080"
